### ISSUE TITLE
Hochkommata in Tabellenfeldern

### ISSUE THREAD

**Issue by pmaanen** [wegbereiter/synode-anmeldung#1]
Ich manchen Tabellenfeldern (zB Namen wird dem Anfang des Inhaltes ein Hochkomma gesetzt.

**Comment by eXaminator** [comment]
Ja, ist bewusst so. Damit wird Excel (bzw. Google Tabellen, Open Office usw.) dazu gezwungen dieses Feld als Textfeld zu betrachten (wichtig z.B. bei Telefonnummern, wegen der führenden 0). In der formatierten Darstellung wird das Hochkomma deshalb nicht angezeigt.
