### ISSUE TITLE
Anmeldung ohne AGB Zustimmung möglich

### ISSUE THREAD

**Issue by pmaanen** [wegbereiter/synode-anmeldung#2]
Wird zwar in der Tabelle vermerkt, aber wird nicht vorher abgefangen.

**Comment by eXaminator** [comment]
Eigentlich sollte der Browser das abfangen und das Absenden des Formulars gar nicht erst zulassen. Im aktuellen Chrome klappt es jedenfalls. In welchem Browser hast du das beobachtet?

**Comment by pmaanen** [comment]
Safari auf iPhone.

**Comment by eXaminator** [comment]
Mh... ok, dann werde ich wohl eine manuelle Validierung einbauen und mich nicht darauf verlassen das User halbwegs aktuelle Browser benutzen ;) Wird aber vermutlich erst Mitte kommender Woche soweit sein.
